---
baseurl: "http://joemphilips.com"
contentdir: "content/"
title: "Joe Miyamoto Philips's blog"
theme: "purehugo"
footnotereturnlinkcontens: "â†©"
paramlinks:
    post: /year/:month/:title/
params:
    Subtitle: "Purpose of the life is to not think about Purpose of life"
    AuthorName: "Joe Miyamoto Philips"
    GitHubUser: "joemphilips"
    SidebarRecentLimit: 5
    twitterName: "joemphilips"
    google_analytics: "UA-70447645-1"
languageCode: "ja"
countryCode: "ja"
...
